### ISSUE TITLE
bad module definition ... vaker/example.v is defined as module `main`

### ISSUE THREAD

**Issue by everton** [ChAoSUnItY/vaker#2]
I'm very new to the language, so maybe I'm doing something wrong here, but after installing the module with both:

```
v install ChAoSUnItY.vaker
```

or

```
v install --git https://github.com/ChAoSUnItY/vaker
```

and importing it on any file, I got the error that says:

```
builder error: bad module definition: testing-vaker-module.v imports module "vaker" but /home/everton/.vmodules/chaosunity/vaker/example.v is defined as module `main
```

(or in the case of installing it with git, it installs directly under ~/.vmodules/vaker - without the chaosunity/ before the folder, but the error is the same)

Should the module be installed in any other way? 

**UPDATE:** this was tested with 

```
$ v --version
V 0.4.0 7ca23f6
```

(other modules installed in the same way seems to work fine)

**Comment by ChAoSUnItY** [comment]
Hello, your installation is correct, it's an library module error caused by examples I provided in vaker, which causes compiler confused on building, I'll fix them soon.
